### ISSUE TITLE
When running "dotnet run" on the QuickConsoleTest LocatePython can't find it

### ISSUE THREAD

**Issue by shanselman** [tonybaloney/CSnakes#125]
When running "dotnet run" on the QuickConsoleTest LocatePython can't find it.

Seems like this (line 11) can't work because it's looking for upper case python with a version and the linux path contains no version (windows does?)

```
namespace CSnakes.Runtime.Locators;
internal class PathLocator(Version version) : PythonLocator(version)
{
    public override PythonLocationMetadata LocatePython()
    {
        var path = Environment.GetEnvironmentVariable("PATH");
        if (string.IsNullOrEmpty(path))
        {
            throw new NullReferenceException("PATH environment variable not found.");
        }
        var pythonPath = path.Split(';').FirstOrDefault(p => p.Contains("Python" + Version));
        if (string.IsNullOrEmpty(pythonPath))
        {
            throw new DirectoryNotFoundException($"Python {Version} not found in PATH.");
        }

        return LocatePythonInternal(pythonPath);
    }
}
```

But this console app doesn't refer to the projects, it refers to the published nugets. So if I tried to hook it up to the project reference (and use this console as an ersatz test, I can't get the project to build. This may be an issue with the devcontainer, wsl, or the a moment in time API change

**Comment by shanselman** [comment]
To be clear, the integration tests all work, but just running "dotnet run" in the examples folder doesn't on WSL/within a DevContainer.

**Comment by tonybaloney** [comment]
Is this with the bundled devcontainer?

The integration tests use the Enviroment Variable Locator, which we've set at the environment variable that GitHub Actions uses:
`https://github.com/tonybaloney/CSnakes/blob/main/src/Integration.Tests/IntegrationTestBase.cs#L27`

Then I've set that same ENV VAR (it's not a standard one) in the DevContainer: [1](https://github.com/tonybaloney/CSnakes/blob/main/.devcontainer/devcontainer.json#L44)

`.FromPath` has been problematic because the folder structures are all over the place between distros.

It looks like I need to update the console sample to use the environment variable that the integration tests use https://github.com/tonybaloney/CSnakes/blob/main/samples/QuickConsoleTest/Program.cs#L19
